# SPDX-FileCopyrightText: (c) 2026 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

self-hosted-runner:
  labels:
    - mlir-large-runner-lang
    - n150
    - bh-loudbox-viommu
    - exabox-multihost-ci-sc1
    - tt-ubuntu-2204-*-stable
