#!/bin/bash
# SPDX-FileCopyrightText: (c) 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0
#
# Fix hardcoded paths in build/env/activate for use in a different workspace.
#
# build/env/activate is generated by CMake with absolute paths from the build
# runner (e.g. /home/runner/work/tt-lang/tt-lang). When the build artifacts
# are extracted in a container with a different workspace path (e.g.
# /__w/tt-lang/tt-lang), these paths must be rewritten.
#
# Usage: fix-activate-paths.sh [build-dir]
#   build-dir  Path to the build directory (default: ./build)

set -e

BUILD_DIR="${1:-build}"
ACTIVATE="$BUILD_DIR/env/activate"

if [ ! -f "$ACTIVATE" ]; then
    echo "ERROR: $ACTIVATE not found" >&2
    exit 1
fi

CONTAINER_WS="$(pwd)"

# The build runner workspace is the parent of CMAKE_BINARY_DIR. Extract it
# from the activate script by finding the first absolute path that ends with
# the build directory name.
BUILD_RUNNER_WS=$(grep -oP '/[^ :"]+(?=/build)' "$ACTIVATE" | head -1)

if [ -z "$BUILD_RUNNER_WS" ]; then
    echo "WARNING: Could not detect build runner workspace path in $ACTIVATE"
    exit 0
fi

if [ "$BUILD_RUNNER_WS" = "$CONTAINER_WS" ]; then
    echo "Paths already match ($CONTAINER_WS), no fixup needed"
    exit 0
fi

sed -i "s|${BUILD_RUNNER_WS}|${CONTAINER_WS}|g" "$ACTIVATE"
echo "Fixed activate paths: $BUILD_RUNNER_WS -> $CONTAINER_WS"
