// RUN: ttlang-opt %s --split-input-file --ttkernel-verify-hardware-config | FileCheck %s
// Generated by Inputs/gen_verify_hardware_config.py; do not edit.
// Summary: MathInit matrix cases that the path-enumerating oracle accepts.
// Cases: 91.

// Consumer copy, equal writer, straight.
// CHECK-LABEL: func.func @copy_equal_straight
func.func @copy_equal_straight(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  ttkernel.copy_tile(%cb_a, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer copy, equal writer, if_both.
// CHECK-LABEL: func.func @copy_equal_if_both
func.func @copy_equal_if_both(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.if %cond {
    ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  } else {
    ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.copy_tile(%cb_a, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer copy, equal writer, if_join_with_required.
// CHECK-LABEL: func.func @copy_equal_if_join_with_required
func.func @copy_equal_if_join_with_required(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.if %cond {
    ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.copy_tile(%cb_a, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer copy, equal writer, for_hoisted_static.
// CHECK-LABEL: func.func @copy_equal_for_hoisted_static
func.func @copy_equal_for_hoisted_static(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %c2 step %c1 {
    ttkernel.copy_tile(%cb_a, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  }
  func.return
}

// -----

// Consumer copy, equal writer, for_hoisted_dynamic.
// CHECK-LABEL: func.func @copy_equal_for_hoisted_dynamic
func.func @copy_equal_for_hoisted_dynamic(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.copy_tile(%cb_a, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  }
  func.return
}

// -----

// Consumer copy, equal writer, for_inside.
// CHECK-LABEL: func.func @copy_equal_for_inside
func.func @copy_equal_for_inside(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    ttkernel.copy_tile(%cb_a, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  }
  func.return
}

// -----

// Consumer copy, equal writer, for_backedge.
// CHECK-LABEL: func.func @copy_equal_for_backedge
func.func @copy_equal_for_backedge(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.copy_tile(%cb_a, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
    ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  func.return
}

// -----

// Consumer copy, equal writer, for_exit_static.
// CHECK-LABEL: func.func @copy_equal_for_exit_static
func.func @copy_equal_for_exit_static(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.for %i0 = %c0 to %c2 step %c1 {
    ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.copy_tile(%cb_a, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer copy, equal writer, for_exit_dynamic.
// CHECK-LABEL: func.func @copy_equal_for_exit_dynamic
func.func @copy_equal_for_exit_dynamic(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.copy_tile(%cb_a, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer copy, equal writer, while_after_writes.
// CHECK-LABEL: func.func @copy_equal_while_after_writes
func.func @copy_equal_while_after_writes(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.while : () -> () {
    scf.condition(%cond)
  } do {
    ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    scf.yield
  }
  ttkernel.copy_tile(%cb_a, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer copy, equal writer, while_before_writes.
// CHECK-LABEL: func.func @copy_equal_while_before_writes
func.func @copy_equal_while_before_writes(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.while : () -> () {
    ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    scf.condition(%cond)
  } do {
    scf.yield
  }
  ttkernel.copy_tile(%cb_a, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer copy, equal writer, while_before_reads.
// CHECK-LABEL: func.func @copy_equal_while_before_reads
func.func @copy_equal_while_before_reads(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.while : () -> () {
    ttkernel.copy_tile(%cb_a, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
    scf.condition(%cond)
  } do {
    scf.yield
  }
  func.return
}

// -----

// Consumer copy, equal writer, while_after_reads.
// CHECK-LABEL: func.func @copy_equal_while_after_reads
func.func @copy_equal_while_after_reads(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.while : () -> () {
    scf.condition(%cond)
  } do {
    ttkernel.copy_tile_init(%cb_a) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    ttkernel.copy_tile(%cb_a, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
    scf.yield
  }
  func.return
}

// -----

// Consumer exp, equal writer, straight.
// CHECK-LABEL: func.func @exp_equal_straight
func.func @exp_equal_straight(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.exp_tile_init() {approx = true} : () -> ()
  ttkernel.exp_tile(%c0) {approx = true} : (index) -> ()
  func.return
}

// -----

// Consumer exp, equal writer, if_both.
// CHECK-LABEL: func.func @exp_equal_if_both
func.func @exp_equal_if_both(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.if %cond {
    ttkernel.exp_tile_init() {approx = true} : () -> ()
  } else {
    ttkernel.exp_tile_init() {approx = true} : () -> ()
  }
  ttkernel.exp_tile(%c0) {approx = true} : (index) -> ()
  func.return
}

// -----

// Consumer exp, equal writer, if_join_with_required.
// CHECK-LABEL: func.func @exp_equal_if_join_with_required
func.func @exp_equal_if_join_with_required(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.exp_tile_init() {approx = true} : () -> ()
  scf.if %cond {
    ttkernel.exp_tile_init() {approx = true} : () -> ()
  }
  ttkernel.exp_tile(%c0) {approx = true} : (index) -> ()
  func.return
}

// -----

// Consumer exp, equal writer, for_hoisted_static.
// CHECK-LABEL: func.func @exp_equal_for_hoisted_static
func.func @exp_equal_for_hoisted_static(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.exp_tile_init() {approx = true} : () -> ()
  scf.for %i0 = %c0 to %c2 step %c1 {
    ttkernel.exp_tile(%c0) {approx = true} : (index) -> ()
  }
  func.return
}

// -----

// Consumer exp, equal writer, for_hoisted_dynamic.
// CHECK-LABEL: func.func @exp_equal_for_hoisted_dynamic
func.func @exp_equal_for_hoisted_dynamic(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.exp_tile_init() {approx = true} : () -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.exp_tile(%c0) {approx = true} : (index) -> ()
  }
  func.return
}

// -----

// Consumer exp, equal writer, for_inside.
// CHECK-LABEL: func.func @exp_equal_for_inside
func.func @exp_equal_for_inside(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.exp_tile_init() {approx = true} : () -> ()
    ttkernel.exp_tile(%c0) {approx = true} : (index) -> ()
  }
  func.return
}

// -----

// Consumer exp, equal writer, for_backedge.
// CHECK-LABEL: func.func @exp_equal_for_backedge
func.func @exp_equal_for_backedge(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.exp_tile_init() {approx = true} : () -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.exp_tile(%c0) {approx = true} : (index) -> ()
    ttkernel.exp_tile_init() {approx = true} : () -> ()
  }
  func.return
}

// -----

// Consumer exp, equal writer, for_exit_static.
// CHECK-LABEL: func.func @exp_equal_for_exit_static
func.func @exp_equal_for_exit_static(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.for %i0 = %c0 to %c2 step %c1 {
    ttkernel.exp_tile_init() {approx = true} : () -> ()
  }
  ttkernel.exp_tile(%c0) {approx = true} : (index) -> ()
  func.return
}

// -----

// Consumer exp, equal writer, for_exit_dynamic.
// CHECK-LABEL: func.func @exp_equal_for_exit_dynamic
func.func @exp_equal_for_exit_dynamic(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.exp_tile_init() {approx = true} : () -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.exp_tile_init() {approx = true} : () -> ()
  }
  ttkernel.exp_tile(%c0) {approx = true} : (index) -> ()
  func.return
}

// -----

// Consumer exp, equal writer, while_after_writes.
// CHECK-LABEL: func.func @exp_equal_while_after_writes
func.func @exp_equal_while_after_writes(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.exp_tile_init() {approx = true} : () -> ()
  scf.while : () -> () {
    scf.condition(%cond)
  } do {
    ttkernel.exp_tile_init() {approx = true} : () -> ()
    scf.yield
  }
  ttkernel.exp_tile(%c0) {approx = true} : (index) -> ()
  func.return
}

// -----

// Consumer exp, equal writer, while_before_writes.
// CHECK-LABEL: func.func @exp_equal_while_before_writes
func.func @exp_equal_while_before_writes(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.while : () -> () {
    ttkernel.exp_tile_init() {approx = true} : () -> ()
    scf.condition(%cond)
  } do {
    scf.yield
  }
  ttkernel.exp_tile(%c0) {approx = true} : (index) -> ()
  func.return
}

// -----

// Consumer exp, equal writer, while_before_reads.
// CHECK-LABEL: func.func @exp_equal_while_before_reads
func.func @exp_equal_while_before_reads(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.exp_tile_init() {approx = true} : () -> ()
  scf.while : () -> () {
    ttkernel.exp_tile(%c0) {approx = true} : (index) -> ()
    scf.condition(%cond)
  } do {
    scf.yield
  }
  func.return
}

// -----

// Consumer exp, equal writer, while_after_reads.
// CHECK-LABEL: func.func @exp_equal_while_after_reads
func.func @exp_equal_while_after_reads(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.while : () -> () {
    scf.condition(%cond)
  } do {
    ttkernel.exp_tile_init() {approx = true} : () -> ()
    ttkernel.exp_tile(%c0) {approx = true} : (index) -> ()
    scf.yield
  }
  func.return
}

// -----

// Consumer add, equal writer, straight.
// CHECK-LABEL: func.func @add_equal_straight
func.func @add_equal_straight(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  ttkernel.add_tiles(%cb_a, %cb_b, %c0, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer add, equal writer, if_both.
// CHECK-LABEL: func.func @add_equal_if_both
func.func @add_equal_if_both(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.if %cond {
    ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  } else {
    ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.add_tiles(%cb_a, %cb_b, %c0, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer add, equal writer, if_join_with_required.
// CHECK-LABEL: func.func @add_equal_if_join_with_required
func.func @add_equal_if_join_with_required(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.if %cond {
    ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.add_tiles(%cb_a, %cb_b, %c0, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer add, equal writer, for_hoisted_static.
// CHECK-LABEL: func.func @add_equal_for_hoisted_static
func.func @add_equal_for_hoisted_static(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %c2 step %c1 {
    ttkernel.add_tiles(%cb_a, %cb_b, %c0, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  }
  func.return
}

// -----

// Consumer add, equal writer, for_hoisted_dynamic.
// CHECK-LABEL: func.func @add_equal_for_hoisted_dynamic
func.func @add_equal_for_hoisted_dynamic(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.add_tiles(%cb_a, %cb_b, %c0, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  }
  func.return
}

// -----

// Consumer add, equal writer, for_inside.
// CHECK-LABEL: func.func @add_equal_for_inside
func.func @add_equal_for_inside(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    ttkernel.add_tiles(%cb_a, %cb_b, %c0, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  }
  func.return
}

// -----

// Consumer add, equal writer, for_backedge.
// CHECK-LABEL: func.func @add_equal_for_backedge
func.func @add_equal_for_backedge(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.add_tiles(%cb_a, %cb_b, %c0, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
    ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  func.return
}

// -----

// Consumer add, equal writer, for_exit_static.
// CHECK-LABEL: func.func @add_equal_for_exit_static
func.func @add_equal_for_exit_static(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.for %i0 = %c0 to %c2 step %c1 {
    ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.add_tiles(%cb_a, %cb_b, %c0, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer add, equal writer, for_exit_dynamic.
// CHECK-LABEL: func.func @add_equal_for_exit_dynamic
func.func @add_equal_for_exit_dynamic(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.add_tiles(%cb_a, %cb_b, %c0, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer add, equal writer, while_after_writes.
// CHECK-LABEL: func.func @add_equal_while_after_writes
func.func @add_equal_while_after_writes(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.while : () -> () {
    scf.condition(%cond)
  } do {
    ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    scf.yield
  }
  ttkernel.add_tiles(%cb_a, %cb_b, %c0, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer add, equal writer, while_before_writes.
// CHECK-LABEL: func.func @add_equal_while_before_writes
func.func @add_equal_while_before_writes(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.while : () -> () {
    ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    scf.condition(%cond)
  } do {
    scf.yield
  }
  ttkernel.add_tiles(%cb_a, %cb_b, %c0, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer add, equal writer, while_before_reads.
// CHECK-LABEL: func.func @add_equal_while_before_reads
func.func @add_equal_while_before_reads(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.while : () -> () {
    ttkernel.add_tiles(%cb_a, %cb_b, %c0, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
    scf.condition(%cond)
  } do {
    scf.yield
  }
  func.return
}

// -----

// Consumer add, equal writer, while_after_reads.
// CHECK-LABEL: func.func @add_equal_while_after_reads
func.func @add_equal_while_after_reads(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.while : () -> () {
    scf.condition(%cond)
  } do {
    ttkernel.add_tiles_init(%cb_a, %cb_b) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    ttkernel.add_tiles(%cb_a, %cb_b, %c0, %c0, %c0) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
    scf.yield
  }
  func.return
}

// -----

// Consumer bcast, equal writer, straight.
// CHECK-LABEL: func.func @bcast_equal_straight
func.func @bcast_equal_straight(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer bcast, equal writer, if_both.
// CHECK-LABEL: func.func @bcast_equal_if_both
func.func @bcast_equal_if_both(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.if %cond {
    ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  } else {
    ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer bcast, equal writer, if_join_with_required.
// CHECK-LABEL: func.func @bcast_equal_if_join_with_required
func.func @bcast_equal_if_join_with_required(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.if %cond {
    ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer bcast, equal writer, for_hoisted_static.
// CHECK-LABEL: func.func @bcast_equal_for_hoisted_static
func.func @bcast_equal_for_hoisted_static(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %c2 step %c1 {
    ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  }
  func.return
}

// -----

// Consumer bcast, equal writer, for_hoisted_dynamic.
// CHECK-LABEL: func.func @bcast_equal_for_hoisted_dynamic
func.func @bcast_equal_for_hoisted_dynamic(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  }
  func.return
}

// -----

// Consumer bcast, equal writer, for_inside.
// CHECK-LABEL: func.func @bcast_equal_for_inside
func.func @bcast_equal_for_inside(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  }
  func.return
}

// -----

// Consumer bcast, equal writer, for_backedge.
// CHECK-LABEL: func.func @bcast_equal_for_backedge
func.func @bcast_equal_for_backedge(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
    ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  func.return
}

// -----

// Consumer bcast, equal writer, for_exit_static.
// CHECK-LABEL: func.func @bcast_equal_for_exit_static
func.func @bcast_equal_for_exit_static(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.for %i0 = %c0 to %c2 step %c1 {
    ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer bcast, equal writer, for_exit_dynamic.
// CHECK-LABEL: func.func @bcast_equal_for_exit_dynamic
func.func @bcast_equal_for_exit_dynamic(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer bcast, equal writer, while_after_writes.
// CHECK-LABEL: func.func @bcast_equal_while_after_writes
func.func @bcast_equal_while_after_writes(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.while : () -> () {
    scf.condition(%cond)
  } do {
    ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    scf.yield
  }
  ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer bcast, equal writer, while_before_writes.
// CHECK-LABEL: func.func @bcast_equal_while_before_writes
func.func @bcast_equal_while_before_writes(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.while : () -> () {
    ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    scf.condition(%cond)
  } do {
    scf.yield
  }
  ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer bcast, equal writer, while_before_reads.
// CHECK-LABEL: func.func @bcast_equal_while_before_reads
func.func @bcast_equal_while_before_reads(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.while : () -> () {
    ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
    scf.condition(%cond)
  } do {
    scf.yield
  }
  func.return
}

// -----

// Consumer bcast, equal writer, while_after_reads.
// CHECK-LABEL: func.func @bcast_equal_while_after_reads
func.func @bcast_equal_while_after_reads(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.while : () -> () {
    scf.condition(%cond)
  } do {
    ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
    scf.yield
  }
  func.return
}

// -----

// Consumer bcast, unkeyed writer, straight.
// CHECK-LABEL: func.func @bcast_unkeyed_straight
func.func @bcast_unkeyed_straight(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_b, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer bcast, unkeyed writer, if_both.
// CHECK-LABEL: func.func @bcast_unkeyed_if_both
func.func @bcast_unkeyed_if_both(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.if %cond {
    ttkernel.unary_bcast_init(%cb_a, %cb_b, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  } else {
    ttkernel.unary_bcast_init(%cb_a, %cb_b, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer bcast, unkeyed writer, if_join_with_required.
// CHECK-LABEL: func.func @bcast_unkeyed_if_join_with_required
func.func @bcast_unkeyed_if_join_with_required(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.if %cond {
    ttkernel.unary_bcast_init(%cb_a, %cb_b, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer bcast, unkeyed writer, for_hoisted_static.
// CHECK-LABEL: func.func @bcast_unkeyed_for_hoisted_static
func.func @bcast_unkeyed_for_hoisted_static(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_b, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %c2 step %c1 {
    ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  }
  func.return
}

// -----

// Consumer bcast, unkeyed writer, for_hoisted_dynamic.
// CHECK-LABEL: func.func @bcast_unkeyed_for_hoisted_dynamic
func.func @bcast_unkeyed_for_hoisted_dynamic(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_b, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  }
  func.return
}

// -----

// Consumer bcast, unkeyed writer, for_inside.
// CHECK-LABEL: func.func @bcast_unkeyed_for_inside
func.func @bcast_unkeyed_for_inside(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.unary_bcast_init(%cb_a, %cb_b, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  }
  func.return
}

// -----

// Consumer bcast, unkeyed writer, for_backedge.
// CHECK-LABEL: func.func @bcast_unkeyed_for_backedge
func.func @bcast_unkeyed_for_backedge(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
    ttkernel.unary_bcast_init(%cb_a, %cb_b, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  func.return
}

// -----

// Consumer bcast, unkeyed writer, for_exit_static.
// CHECK-LABEL: func.func @bcast_unkeyed_for_exit_static
func.func @bcast_unkeyed_for_exit_static(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.for %i0 = %c0 to %c2 step %c1 {
    ttkernel.unary_bcast_init(%cb_a, %cb_b, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer bcast, unkeyed writer, for_exit_dynamic.
// CHECK-LABEL: func.func @bcast_unkeyed_for_exit_dynamic
func.func @bcast_unkeyed_for_exit_dynamic(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.unary_bcast_init(%cb_a, %cb_b, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer bcast, unkeyed writer, while_after_writes.
// CHECK-LABEL: func.func @bcast_unkeyed_while_after_writes
func.func @bcast_unkeyed_while_after_writes(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_c, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.while : () -> () {
    scf.condition(%cond)
  } do {
    ttkernel.unary_bcast_init(%cb_a, %cb_b, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    scf.yield
  }
  ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer bcast, unkeyed writer, while_before_writes.
// CHECK-LABEL: func.func @bcast_unkeyed_while_before_writes
func.func @bcast_unkeyed_while_before_writes(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.while : () -> () {
    ttkernel.unary_bcast_init(%cb_a, %cb_b, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    scf.condition(%cond)
  } do {
    scf.yield
  }
  ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
  func.return
}

// -----

// Consumer bcast, unkeyed writer, while_before_reads.
// CHECK-LABEL: func.func @bcast_unkeyed_while_before_reads
func.func @bcast_unkeyed_while_before_reads(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.unary_bcast_init(%cb_a, %cb_b, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.while : () -> () {
    ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
    scf.condition(%cond)
  } do {
    scf.yield
  }
  func.return
}

// -----

// Consumer bcast, unkeyed writer, while_after_reads.
// CHECK-LABEL: func.func @bcast_unkeyed_while_after_reads
func.func @bcast_unkeyed_while_after_reads(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.while : () -> () {
    scf.condition(%cond)
  } do {
    ttkernel.unary_bcast_init(%cb_a, %cb_b, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    ttkernel.unary_bcast(%cb_a, %c0, %c0, <col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index) -> ()
    scf.yield
  }
  func.return
}

// -----

// Consumer reduce, equal writer, straight.
// CHECK-LABEL: func.func @reduce_equal_straight
func.func @reduce_equal_straight(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer reduce, equal writer, if_both.
// CHECK-LABEL: func.func @reduce_equal_if_both
func.func @reduce_equal_if_both(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.if %cond {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  } else {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer reduce, equal writer, if_join_with_required.
// CHECK-LABEL: func.func @reduce_equal_if_join_with_required
func.func @reduce_equal_if_join_with_required(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.if %cond {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer reduce, equal writer, for_hoisted_static.
// CHECK-LABEL: func.func @reduce_equal_for_hoisted_static
func.func @reduce_equal_for_hoisted_static(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %c2 step %c1 {
    ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  }
  func.return
}

// -----

// Consumer reduce, equal writer, for_hoisted_dynamic.
// CHECK-LABEL: func.func @reduce_equal_for_hoisted_dynamic
func.func @reduce_equal_for_hoisted_dynamic(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  }
  func.return
}

// -----

// Consumer reduce, equal writer, for_inside.
// CHECK-LABEL: func.func @reduce_equal_for_inside
func.func @reduce_equal_for_inside(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  }
  func.return
}

// -----

// Consumer reduce, equal writer, for_backedge.
// CHECK-LABEL: func.func @reduce_equal_for_backedge
func.func @reduce_equal_for_backedge(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  func.return
}

// -----

// Consumer reduce, equal writer, for_exit_static.
// CHECK-LABEL: func.func @reduce_equal_for_exit_static
func.func @reduce_equal_for_exit_static(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.for %i0 = %c0 to %c2 step %c1 {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer reduce, equal writer, for_exit_dynamic.
// CHECK-LABEL: func.func @reduce_equal_for_exit_dynamic
func.func @reduce_equal_for_exit_dynamic(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer reduce, equal writer, while_after_writes.
// CHECK-LABEL: func.func @reduce_equal_while_after_writes
func.func @reduce_equal_while_after_writes(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.while : () -> () {
    scf.condition(%cond)
  } do {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    scf.yield
  }
  ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer reduce, equal writer, while_before_writes.
// CHECK-LABEL: func.func @reduce_equal_while_before_writes
func.func @reduce_equal_while_before_writes(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.while : () -> () {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    scf.condition(%cond)
  } do {
    scf.yield
  }
  ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer reduce, equal writer, while_before_reads.
// CHECK-LABEL: func.func @reduce_equal_while_before_reads
func.func @reduce_equal_while_before_reads(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.while : () -> () {
    ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
    scf.condition(%cond)
  } do {
    scf.yield
  }
  func.return
}

// -----

// Consumer reduce, equal writer, while_after_reads.
// CHECK-LABEL: func.func @reduce_equal_while_after_reads
func.func @reduce_equal_while_after_reads(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.while : () -> () {
    scf.condition(%cond)
  } do {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
    scf.yield
  }
  func.return
}

// -----

// Consumer reduce, unkeyed writer, straight.
// CHECK-LABEL: func.func @reduce_unkeyed_straight
func.func @reduce_unkeyed_straight(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_a, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer reduce, unkeyed writer, if_both.
// CHECK-LABEL: func.func @reduce_unkeyed_if_both
func.func @reduce_unkeyed_if_both(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.if %cond {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_a, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  } else {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_a, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer reduce, unkeyed writer, if_join_with_required.
// CHECK-LABEL: func.func @reduce_unkeyed_if_join_with_required
func.func @reduce_unkeyed_if_join_with_required(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.if %cond {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_a, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer reduce, unkeyed writer, for_hoisted_static.
// CHECK-LABEL: func.func @reduce_unkeyed_for_hoisted_static
func.func @reduce_unkeyed_for_hoisted_static(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_a, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %c2 step %c1 {
    ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  }
  func.return
}

// -----

// Consumer reduce, unkeyed writer, for_hoisted_dynamic.
// CHECK-LABEL: func.func @reduce_unkeyed_for_hoisted_dynamic
func.func @reduce_unkeyed_for_hoisted_dynamic(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_a, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  }
  func.return
}

// -----

// Consumer reduce, unkeyed writer, for_inside.
// CHECK-LABEL: func.func @reduce_unkeyed_for_inside
func.func @reduce_unkeyed_for_inside(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_a, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  }
  func.return
}

// -----

// Consumer reduce, unkeyed writer, for_backedge.
// CHECK-LABEL: func.func @reduce_unkeyed_for_backedge
func.func @reduce_unkeyed_for_backedge(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_a, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  func.return
}

// -----

// Consumer reduce, unkeyed writer, for_exit_static.
// CHECK-LABEL: func.func @reduce_unkeyed_for_exit_static
func.func @reduce_unkeyed_for_exit_static(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.for %i0 = %c0 to %c2 step %c1 {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_a, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer reduce, unkeyed writer, for_exit_dynamic.
// CHECK-LABEL: func.func @reduce_unkeyed_for_exit_dynamic
func.func @reduce_unkeyed_for_exit_dynamic(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.for %i0 = %c0 to %n step %c1 {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_a, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  }
  ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer reduce, unkeyed writer, while_after_writes.
// CHECK-LABEL: func.func @reduce_unkeyed_while_after_writes
func.func @reduce_unkeyed_while_after_writes(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_c, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.while : () -> () {
    scf.condition(%cond)
  } do {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_a, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    scf.yield
  }
  ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer reduce, unkeyed writer, while_before_writes.
// CHECK-LABEL: func.func @reduce_unkeyed_while_before_writes
func.func @reduce_unkeyed_while_before_writes(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.while : () -> () {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_a, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    scf.condition(%cond)
  } do {
    scf.yield
  }
  ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
  func.return
}

// -----

// Consumer reduce, unkeyed writer, while_before_reads.
// CHECK-LABEL: func.func @reduce_unkeyed_while_before_reads
func.func @reduce_unkeyed_while_before_reads(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  ttkernel.reduce_init(%cb_a, %cb_b, %cb_a, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
  scf.while : () -> () {
    ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
    scf.condition(%cond)
  } do {
    scf.yield
  }
  func.return
}

// -----

// Consumer reduce, unkeyed writer, while_after_reads.
// CHECK-LABEL: func.func @reduce_unkeyed_while_after_reads
func.func @reduce_unkeyed_while_after_reads(%cond: i1, %n: index) {
  %cb_a = ttkernel.get_compile_time_arg_val(0) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_b = ttkernel.get_compile_time_arg_val(1) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %cb_c = ttkernel.get_compile_time_arg_val(2) : () -> !ttkernel.cb<4, !ttcore.tile<32x32, f32>>
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  scf.while : () -> () {
    scf.condition(%cond)
  } do {
    ttkernel.reduce_init(%cb_a, %cb_b, %cb_a, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>) -> ()
    ttkernel.reduce_tile(%cb_a, %cb_b, %c0, %c0, %c0, <reduce_sum>, <reduce_dim_col>) : (!ttkernel.cb<4, !ttcore.tile<32x32, f32>>, !ttkernel.cb<4, !ttcore.tile<32x32, f32>>, index, index, index) -> ()
    scf.yield
  }
  func.return
}
