#!/usr/bin/env python3
# SPDX-FileCopyrightText: (c) 2026 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
#
# Build the pure-Python tt-lang-sim wheel: simulator runtime + bundled
# tutorials, no compiler. Sources are staged under packaging/sim/build/stage/
# (gitignored via **/build). The hardware tt-lang wheel is built from the
# repository root via CMake and is unaffected by this script.

import os
import pathlib
import shutil
import subprocess
import sys

from setuptools import setup

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from rewrite_readme import absolutize_readme_images, ref_for_version  # noqa: E402

PKG_ROOT = pathlib.Path(__file__).resolve().parent
REPO_ROOT = PKG_ROOT.parent.parent
STAGE = PKG_ROOT / "build" / "stage"


def get_version() -> str:
    pretend = os.environ.get("TTLANG_PRETEND_VERSION", "").strip()
    if pretend:
        return pretend
    try:
        tag = (
            subprocess.check_output(
                ["git", "describe", "--tags", "--match", "v[0-9]*", "--abbrev=0"],
                stderr=subprocess.DEVNULL,
                text=True,
                cwd=str(REPO_ROOT),
            )
            .strip()
            .lstrip("v")
        )
        commits = subprocess.check_output(
            ["git", "rev-list", f"v{tag}..HEAD", "--count"],
            stderr=subprocess.DEVNULL,
            text=True,
            cwd=str(REPO_ROOT),
        ).strip()
        base, sep, local = tag.partition("+")
        local_suffix = f"+{local}" if sep else ""
        if commits and commits != "0":
            return f"{base}.dev{commits}{local_suffix}"
        return f"{base}{local_suffix}"
    except Exception:
        return "0.2.0.dev0"


VERSION = get_version()


def stage() -> None:
    if STAGE.exists():
        shutil.rmtree(STAGE)
    ttl = STAGE / "ttl"
    ttl.mkdir(parents=True)

    src_ttl = REPO_ROOT / "python" / "ttl"
    for fn in ("__init__.py", "version.py"):
        shutil.copy(src_ttl / fn, ttl / fn)

    (ttl / "config.py").write_text(
        "# Auto-generated by packaging/sim/setup.py\n"
        "HAS_TT_DEVICE = False\n"
        f'VERSION = "{VERSION}"\n'
    )
    (ttl / "_sim_only_marker.py").write_text(
        "# Present only in tt-lang-sim wheel; consumed by ttl/__init__.py.\n"
    )

    shutil.copytree(REPO_ROOT / "python" / "sim", ttl / "sim")
    shutil.copytree(src_ttl / "_pipenets", ttl / "_pipenets")
    shutil.copytree(src_ttl / "_setup", ttl / "_setup")
    shutil.copytree(REPO_ROOT / "python" / "utils", ttl / "utils")
    shutil.copytree(REPO_ROOT / "python" / "sim_stats", STAGE / "sim_stats")

    tutorials = ttl / "tutorials"
    tutorials.mkdir()
    shutil.copy(src_ttl / "tutorials" / "__init__.py", tutorials / "__init__.py")
    for src, dst in (
        ("examples/elementwise-tutorial", "elementwise"),
        ("examples/matmul-tutorial", "matmul"),
        ("examples/tutorial", "broadcast"),
    ):
        shutil.copytree(REPO_ROOT / src, tutorials / dst)


stage()


readme_path = REPO_ROOT / "README.md"
with open(readme_path, "r", encoding="utf-8") as f:
    readme = absolutize_readme_images(f.read(), ref_for_version(VERSION), REPO_ROOT)


def read_runtime_requirements() -> list[str]:
    out: list[str] = []
    for line in (REPO_ROOT / "requirements-runtime.txt").read_text().splitlines():
        s = line.strip()
        if s and not s.startswith("#"):
            out.append(s)
    return out


setup(
    version=VERSION,
    install_requires=read_runtime_requirements(),
    packages=[
        "ttl",
        "ttl._pipenets",
        "ttl._setup",
        "ttl.sim",
        "ttl.tutorials",
        "ttl.tutorials.elementwise",
        "ttl.tutorials.matmul",
        "ttl.tutorials.broadcast",
        "ttl.utils",
        "sim_stats",
    ],
    package_dir={"": str(STAGE.relative_to(PKG_ROOT))},
    long_description=readme,
    long_description_content_type="text/markdown",
    zip_safe=False,
)
