name: Setup macOS Toolchain
description: Install dependencies and build/cache tt-mlir toolchain for macOS

inputs:
  tt-mlir-path:
    description: Path to tt-mlir checkout
    required: true
  toolchain-hash:
    description: Hash of toolchain files for cache key
    required: true

runs:
  using: composite
  steps:
    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        brew install cmake ninja googletest
        python -m pip install --upgrade pip

    - name: Create toolchain directory
      shell: bash
      run: |
        sudo mkdir -p /opt/ttmlir-toolchain
        sudo chown -R $USER /opt/ttmlir-toolchain

    - name: Cache tt-mlir toolchain
      id: cache-toolchain
      uses: actions/cache@v4
      with:
        path: /opt/ttmlir-toolchain
        key: macos-ttmlir-toolchain-${{ inputs.toolchain-hash }}-${{ github.ref_name }}
        restore-keys: |
          macos-ttmlir-toolchain-${{ inputs.toolchain-hash }}

    - name: Check if toolchain was restored
      id: check-toolchain
      shell: bash
      run: |
        if [ -f /opt/ttmlir-toolchain/venv/bin/python3 ] && [ -f /opt/ttmlir-toolchain/bin/llvm-config ]; then
          echo "restored=true" >> $GITHUB_OUTPUT
          echo "Toolchain was restored from cache"
        else
          echo "restored=false" >> $GITHUB_OUTPUT
          echo "Toolchain needs to be built"
        fi

    - name: Build tt-mlir toolchain
      if: steps.check-toolchain.outputs.restored != 'true'
      shell: bash
      run: |
        cd ${{ inputs.tt-mlir-path }}
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release -B env/build env
        cmake --build env/build

    - name: Cleanup toolchain to reduce cache size
      if: steps.check-toolchain.outputs.restored != 'true'
      shell: bash
      run: .github/scripts/cleanup-macos-toolchain.sh
